### SERVER http://localhost:3000

### TEST PAGES
### GET /
GET http://localhost:3000/

### TEST API
### GET /api/todos
GET http://localhost:3000/api/todos

### POST /api/todos
POST http://localhost:3000/api/todos
Content-Type: application/x-www-form-urlencoded

text=Workout

### POST /api/todos/togle/:id
POST http://localhost:3000/api/todos/toggle/8cc4e1a1-9d78-4c6e-ad7d-7d8d3218a466

